from .system_prompts import QUESTION_GENERATION_SYSTEM_PROMPT
from .user_prompts import QUESTION_GENERATION_USER_PROMPT

__all__ = ["QUESTION_GENERATION_SYSTEM_PROMPT", "QUESTION_GENERATION_USER_PROMPT"]
