"""change in mcq and psq fields

Revision ID: c63598a25b33
Revises: 9704afe5740d
Create Date: 2024-12-29 17:36:43.648833

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c63598a25b33"
down_revision: Union[str, None] = "9704afe5740d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "multiple_choice_question",
        sa.Column("difficulty_level", sa.Text(), nullable=True),
    )
    op.drop_column("multiple_choice_question", "question_level")
    op.add_column(
        "problem_solving_questions",
        sa.Column("difficulty_level", sa.Text(), nullable=True),
    )
    op.drop_column("problem_solving_questions", "question_level")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "problem_solving_questions",
        sa.Column("question_level", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_column("problem_solving_questions", "difficulty_level")
    op.add_column(
        "multiple_choice_question",
        sa.Column("question_level", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_column("multiple_choice_question", "difficulty_level")
    # ### end Alembic commands ###
