"""changes in mcq table fields

Revision ID: c7acc6baa11e
Revises: 7cbdfea05625
Create Date: 2024-12-29 14:47:27.298925

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c7acc6baa11e"
down_revision: Union[str, None] = "7cbdfea05625"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
