"""Added New Field in MCQ & PSQ Models

Revision ID: e5505ac9038f
Revises: 932d7528d5a2
Create Date: 2025-01-27 17:54:15.503924

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5505ac9038f"
down_revision: Union[str, None] = "932d7528d5a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "multiple_choice_question",
        sa.Column("required_time", sa.Text(), nullable=False),
    )
    op.add_column(
        "problem_solving_questions",
        sa.Column("required_time", sa.Text(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("problem_solving_questions", "required_time")
    op.drop_column("multiple_choice_question", "required_time")
    # ### end Alembic commands ###
