name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform
      run: terraform plan -var="aws_region=${{ secrets.AWS_REGION }}" -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_KEY }}" -var="s3_bucket_name=${{ secrets.S3_BUCKET_NAME }}" -var="lambda_name=${{ secrets.LAMBDA_NAME }}"

    - name: Apply Terraform
      run: terraform apply -auto-approve -var="aws_region=${{ secrets.AWS_REGION }}" -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_KEY }}" -var="s3_bucket_name=${{ secrets.S3_BUCKET_NAME }}" -var="lambda_name=${{ secrets.LAMBDA_NAME }}"
